### ISSUE TITLE
Crash: Font 'Aharoni' does not support style 'Regular'.

### ISSUE THREAD

**Issue by r0lZ** [SubtitleEdit/subtitleedit#1494]
Stack trace:

Error Message:
Font 'Aharoni' does not support style 'Regular'.

Stack Trace:
   at System.Drawing.Font.CreateNativeFont()

   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)

   at System.Drawing.Font..ctor(String familyName, Single emSize)

   at Nikse.SubtitleEdit.Forms.ExportPngXml.SubtitleListView1Add(Paragraph paragraph)

   at Nikse.SubtitleEdit.Forms.ExportPngXml.SubtitleListView1Fill(Subtitle subtitle)

   at Nikse.SubtitleEdit.Forms.ExportPngXml.Initialize(Subtitle subtitle, SubtitleFormat format, String exportType, String fileName, VideoInfo videoInfo, String videoFileName)

   at Nikse.SubtitleEdit.Forms.Main.ToolStripMenuItemExportPngXmlClick(Object sender, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by niksedk** [comment]
I've updated the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.11/SubtitleEditBetaTest.zip

**Comment by r0lZ** [comment]
Thanks.
I confirm that the problem is solved.
