### ISSUE TITLE
Options not available after Set Video Offset

### ISSUE THREAD

**Issue by mastertigurius** [SubtitleEdit/subtitleedit#1750]
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Nikse.SubtitleEdit.Forms.Settings.AddNode(TreeNode node, String text, String shortcut, Boolean isMenuItem)

   at Nikse.SubtitleEdit.Forms.Settings..ctor()

   at Nikse.SubtitleEdit.Forms.Main.ShowSettings()

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

Start program, open video, set video offset applied, attempt to open Tools>Options.
Issue did not replicate after closing and restarting program.

**Comment by niksedk** [comment]
Do you still get the error in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip ?
