### ISSUE TITLE
Found crash with HVEC movie + MPC-HC x64

### ISSUE THREAD

**Issue by ramon18** [SubtitleEdit/subtitleedit#1780]
An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Input string was not in a correct format.

Stack Trace:
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Nikse.SubtitleEdit.Logic.VideoPlayers.MpcHC.MpcHc.OnCopyData(Object sender, EventArgs e)
   at Nikse.SubtitleEdit.Logic.VideoPlayers.MpcHC.MessageHandlerWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by niksedk** [comment]
@ramon18: Does this solve the issue: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip ?   If yes, does the position slider still work?

**Comment by ramon18** [comment]
@niksedk Nope, the BETA you sent produces the same exception.

Thanks

**Comment by niksedk** [comment]
@ramon18: Could you send the stacktrace... it should now have line numbers

**Comment by niksedk** [comment]
@ramon18: Beta beta up... https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.12/SubtitleEditBeta.zip

**Comment by ramon18** [comment]
MPCHC - multiParam=My \| Movie|||D:\movie.mkv|3017.014

Input string was not in a correct format.

   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)

   at Nikse.SubtitleEdit.Logic.VideoPlayers.MpcHC.MpcHc.OnCopyData(Object sender, EventArgs e) in C:\Data\SubtitleEdit\subtitleedit\src\Logic\VideoPlayers\MpcHC\MpcHc.cs:line 172
