### ISSUE TITLE
Error exporting Final Cut Pro + image in 3.4.13

### ISSUE THREAD

**Issue by imyourshadow** [SubtitleEdit/subtitleedit#1790]
When I try to export subtitle to Final Cut Pro + image I get the the error message below.
This issue was not present in 3.4.12 and when I reinstalled it I was able to export the same subtitles just fine.

---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Input string was not in a correct format.

Stack Trace:
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)

   at System.Single.Parse(String s)

   at Nikse.SubtitleEdit.Forms.ExportPngXml.Initialize(Subtitle subtitle, SubtitleFormat format, String exportType, String fileName, VideoInfo videoInfo, String videoFileName)

   at Nikse.SubtitleEdit.Forms.Main.toolStripMenuItemExportFcpIImage_Click(Object sender, EventArgs e)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by xylographe** [comment]
b27317b925760548a456ef7fdc9a31824fdcf061

This cannot work because the first two items in `comboBoxBorderWidth` are not numbers.

**Comment by niksedk** [comment]
thx imyourshadow +  xylographe :)
