### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by bulkware** [SubtitleEdit/subtitleedit#1987]
I got this error message when running SubtitleEdit 3.4.13 a9544a3 on Windows XP in VirtualBox. The path I was trying to access is mounted from my host OS. I was trying to use the "Batch convert" option and was scanning for files while it crashed.

`---------------------------
## Windows Forms Thread Exception

An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Illegal characters in path.

Stack Trace:
   at System.Security.Permissions.FileIOPermission.HasIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path)
   at Nikse.SubtitleEdit.Forms.BatchConvert.SearchFolder(String path)
   at Nikse.SubtitleEdit.Forms.BatchConvert.SearchFolder(String path)
   at Nikse.SubtitleEdit.Forms.BatchConvert.buttonSearchFolder_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
## Abort   Retry   Ignore   

`

**Comment by xylographe** [comment]
This is a Windows limitation. Some characters, like `"` (double quote), `?` (question mark) and `*` (asterisk), cannot be part of a file or folder name under Windows (Linux/Unix OTOH only prohibit `/` (slash)). The only way to solve this is to rename the ‘invalid’ file/folder name(s).

Of course, SE could handle this exception more gracefully.

**Comment by bulkware** [comment]
Yes, it was a question mark in one of my subdirs. I don't have to use that so problem is solved for me. I will leave this issue still open if you want to handle the exception better.
