### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by naszdom** [SubtitleEdit/subtitleedit#2335]
I got the following error which the programme asked me to report.  As I do not know were to find the logs I had to OCR it:

An application error occurred in Subtitle Edit.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:
Error Message:
Object reference not set to an instance of an object.
Stack Trace:
at NikseSubtitleEdit.Logic.Ocr.OcrFixEngine.SpellCheckOcrText(String line, Bitmap bitmap, String word, Listi suggestions)
at
Nikse.SubtitleEdit.Logic.Ocr.OcrFixEngine.FixUnknownWordsViaGuessOr
Prompt(1nt32& wordsNotFound, String line, 1nt32 index, Bitmap bitmap,
Boolean autoFix, Boolean promptForFixingErrors, Boolean log,
AutoGuessLevel autoGuess)
at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.OcrViaTesseract(Bitmap bitmap, lnt32 index)
at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.MainLoop(1nt32 max, lnt32
at Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.mainOcrTimer...Tick(Object sender, EventArgs e)
at
Nikse.SubtitleEdit.Forms.Ocr.VobSubOcr.ButtonStartOcrClick(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at Systern.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, lnt32 clicks)
at Systern.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System .Win d ows. Forms. Button .Wn d Proc (M essa ge& m)
at Systern.Windows.Forms.NativeWindow.Callback(lntPtr hWnd, 1nt32 msg, lntPtr wparam, lntPtr Iparam)

**Comment by niksedk** [comment]
How can we re-create this error?

**Comment by ivandrofly** [comment]
Looks like this has already been reported https://github.com/SubtitleEdit/subtitleedit/issues/2319

**Comment by niksedk** [comment]
Has been fix in bcf566c96197298681350d5f7f64708c2f7bcce5
Will be fixed in next update - and should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
