### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by dohn** [SubtitleEdit/subtitleedit#2863]
This is the first time Subtitle Edit failed me. I am running Windows XP Pro SP3.

Windows Forms Thread Exception
-----------------------------------
An application error occurred in Subtitle Edit 3.5.6.0.

Error Message:
The requested security protocol is not supported.

Stack Trace:
   at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)

   at Nikse.SubtitleEdit.Forms.Main.Main_Shown(Object sender, EventArgs e)

   at System.Windows.Forms.Form.OnShown(EventArgs e)

   at System.Windows.Forms.Form.CallShownEvent()

   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)

   at System.Threading.ExecutionContext.runTryCode(Object userData)

   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by niksedk** [comment]
Looks like a duplicate: https://github.com/SubtitleEdit/subtitleedit/issues/2799
