### ISSUE TITLE
Statistics for Persian Subtitle

### ISSUE THREAD

**Issue by khashayarxy** [SubtitleEdit/subtitleedit#2997]
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 3.5.6.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
An entry with the same key already exists.

Stack Trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)

   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)

   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)

   at Nikse.SubtitleEdit.Forms.Statistics.CalculateMostUsedLines()

   at Nikse.SubtitleEdit.Forms.Statistics..ctor(Subtitle subtitle, String fileName, SubtitleFormat format)

   at Nikse.SubtitleEdit.Forms.Main.toolStripMenuItemStatistics_Click(Object sender, EventArgs e)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by khashayarxy** [comment]
statistics for Persian works fine in single subtitle but when I join other subtitles with the same language it doesn't show me the statistics. and this error pops up. also, I don't have this problem with English subtitles.

**Comment by niksedk** [comment]
@khashayarxy: thx for the info :)
Could you try latest beta (should hopefully be fixed now): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.6/SubtitleEditBeta.zip

Also, if it still fails - please attach a subtitle that causes this crash.

**Comment by khashayarxy** [comment]
Thank you so much. It's working and it's much faster!

**Comment by niksedk** [comment]
Thx for testing :)
