### ISSUE TITLE
Windows forms thread exception

### ISSUE THREAD

**Issue by indeed-a-genius** [SubtitleEdit/subtitleedit#3152]
When using "Remove text for hearing impaired" on the attached srt subtitles I'm getting an "Windows forms thread exception" error.
[sample-srt.zip](https://github.com/SubtitleEdit/subtitleedit/files/2521205/sample-srt.zip)

I'm on Windows 10 x64

Full error below:
```
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 3.5.7.1. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Index was outside the bounds of the array.

Stack Trace:
   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.RemoveColon(String text)

   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.RemoveTextFromHearImpaired(String text)

   at Nikse.SubtitleEdit.Forms.FormRemoveTextForHearImpaired.GeneratePreview()

   at Nikse.SubtitleEdit.Forms.Main.RemoveTextForHearImpairedToolStripMenuItemClick(Object sender, EventArgs e)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by niksedk** [comment]
thx for the info :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip

**Comment by blaubart2** [comment]
Beta did not help here. I get "Windows forms thread exception" by simply klicking on "Load" or "Save" Button. Also in old 3.5.3.0 even in super old 3.3.0.1 I get "Exceptional error".

Seems to be since Win10 1809 - just tried 3.5.7.1 in Win10 1803 - no issues!

![subted265](https://user-images.githubusercontent.com/44677301/47864003-e2b5e700-ddf8-11e8-9434-83afaa2326de.png)

**Comment by niksedk** [comment]
@blaubart2: I don't think this is related to this thread... but does that also happen if latest beta ( https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.7/SubtitleEditBeta.zip ) and do you use mpv as video player? (if you're not using mpv than perhaps try installing .net framework 4.7.2 )

**Comment by blaubart2** [comment]
Just checked:
- Windows 10 1803 - Net Framework 4.7.03056
- Windows 10 1809 - Net Framework 4.7.03190

So if SubtitleEdit is Net Framework dependend, seems it likes NetF. 4.7.03056 more?
Hoping it helps.

**Comment by blaubart2** [comment]
Just tried latest Beta 3.5.7.107 in Win10 1809 2018-11 Update - still no success.

- klick "open" button brings -> "Windows forms thread exception"
- drag&drop files into open SE works ok / always worked - but
- klick "save" button brings -> "Windows forms thread exception"
- trying most export -> "Windows forms thread exception"
