### ISSUE TITLE
"Remove text for hearing impaired..." exception

### ISSUE THREAD

**Issue by goonis** [SubtitleEdit/subtitleedit#3161]
---------------------------
Windows Forms Thread Exception
--------------

-------------
An application error occurred in Subtitle Edit 3.5.7.1. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Length cannot be less than zero.

Parameter name: length

Stack Trace:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.StartsAndEndsWithHearImpairedTags(String text, Char startTag, Char endTag)
   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.StartsAndEndsWithHearImpairedTags(String text)
   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.RemoveHearImpairedtagsInsideLine(String newText)
   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.RemoveTextFromHearImpaired(String text)
   at Nikse.SubtitleEdit.Forms.FormRemoveTextForHearImpaired.GeneratePreview()
   at Nikse.SubtitleEdit.Forms.Main.RemoveTextForHearImpairedToolStripMenuItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Srt file: [1.zip](https://github.com/SubtitleEdit/subtitleedit/files/2543528/1.zip)

**Comment by marb99** [comment]
On Subtitle Edit 3.5.7 build 78 works fine

![capturar](https://user-images.githubusercontent.com/7856897/47945576-cd28e600-defa-11e8-9137-a49d61293948.PNG)

**Comment by goonis** [comment]
Yes, latest beta works fine, thank you.
