### ISSUE TITLE
ERROR: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#3854]
When using the command line process of Subtitle Edit 3.5.11 I get the following error processing a file.
Media Info of file.
```
 General
Unique ID                                : 89863511209000981205774161931450025377 (0x439B152CC75B4CDA0B4360DD18E985A1)
Complete name                            : C:\TEMP\Torrent\PROCD\test\Castle Rock - S01E01 - [2160p BluRay x265][EPSiLON].mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 17.5 GiB
Duration                                 : 54 min 28 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 46.1 Mb/s
Movie name                               : Castle.Rock.S01E01.Severance.2160p.UHD.BluRay.REMUX.HDR.HEVC.DTS-HD.MA.5.1-EPSiLON
Track name/Position                      : 1
Track name/Total                         : 10
Encoded date                             : UTC 2019-11-27 21:58:47
Writing application                      : mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
Writing library                          : libebml v1.3.9 + libmatroska v1.5.2
IMDB                                     : tt6557554
TMDB                                     : tv/71116
TVDB                                     : 331600

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 54 min 28 s
Bit rate                                 : 43.9 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.221
Stream size                              : 16.7 GiB (95%)
Title                                    : MPEG-H HEVC Video / 43921 kbps / 2160p / 23.976 fps / 16:9 / Main 10 @ Level 5.1 @ High / 10 bits / HDR10 / BT.2020
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 1962 cd/m2
Maximum Frame-Average Light Level        : 227 cd/m2

Audio
ID                                       : 2
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Codec ID                                 : A_DTS
Duration                                 : 54 min 28 s
Bit rate mode                            : Variable
Bit rate                                 : 2 126 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 828 MiB (5%)
Title                                    : DTS-HD Master Audio / 5.1 / 48 kHz / 2126 kbps / 16-bit
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : PGS
Muxing mode                              : zlib
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 54 min 9 s
Bit rate                                 : 23.6 kb/s
Count of elements                        : 988
Stream size                              : 9.14 MiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : PGS
Muxing mode                              : zlib
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 54 min 4 s
Bit rate                                 : 19.6 kb/s
Count of elements                        : 820
Stream size                              : 7.59 MiB (0%)
Language                                 : Dutch
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Chapter 1
00:03:36.049                             : en:Chapter 2
00:10:28.294                             : en:Chapter 3
00:20:05.162                             : en:Chapter 4
00:29:13.210                             : en:Chapter 5
00:39:44.591                             : en:Chapter 6
00:52:17.051                             : en:Chapter 7
```

Command line used
`C:\GitHub\Subtitle Edit>SubtitleEdit.exe /convert *.mkv subrip /inputfolder:"C:\TEMP\Torrent\PROCD\test" /fixcommonerrors /removetextforhi /fixcommonerrors`

It starts the OCR process but crashes at 100%
```
ERROR: Object reference not set to an instance of an object.
   at Nikse.SubtitleEdit.Core.Forms.FixCommonErrors.FixOverlappingDisplayTimes.Fix(Subtitle subtitle, IFixCallbacks callbacks)
   at Nikse.SubtitleEdit.Forms.FixCommonErrors.RunSelectedActions()
   at Nikse.SubtitleEdit.Forms.FixCommonErrors.RunBatch(Subtitle subtitle, SubtitleFormat format, Encoding encoding, String language)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.BatchConvertSave(String targetFormat, TimeSpan offset, Encoding targetEncoding, String outputFolder, Int32 count, Int32& converted, Int32& errors, IEnumerable`1 formats, String fileName, Subtitle sub, SubtitleFormat format, List`1 binaryParagraphs, Boolean overwrite, Int32 pacCodePage, Nullable`1 targetFrameRate, ICollection`1 multipleReplaceImportFiles, BatchAction actions, Nullable`1 resolution, Boolean autoDetectLanguage, BatchConvertProgress progressCallback)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.Convert(String[] arguments)
```

**Comment by niksedk** [comment]
Thanks for the info :)
Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by Rouzax** [comment]
Yes 👍 it works now.
Thanks for the fast help.

PS: Could you also look at: https://github.com/SubtitleEdit/subtitleedit/issues/3818
I can't change my password on your site.

**Comment by xylographe** [comment]
@Rouzax 
Passing the `/FixCommonErrors` option twice does not perform the **FixCommonErrors.RunBatch()** twice. Any enabled text transformations are performed exactly once, in the following order:
- RemoveTextForHI
- RemoveFormatting
- FixCommonErrors
- ReDoCasing
- ReverseRtlStartEnd
- MultipleReplace

**Comment by Rouzax** [comment]
@xylographe Are you sure about that, @niksedk told me in this reply it will execute in the order specified and can be multiple times. https://github.com/SubtitleEdit/subtitleedit/issues/2713#issuecomment-359179826

**Comment by xylographe** [comment]
@Rouzax Yes, I'm sure. See [BatchConvertSave()](https://github.com/SubtitleEdit/subtitleedit/blob/5fbf4a9ad44544fb73d9cb3d3647c80d57a00623/src/Logic/CommandLineConvert/CommandLineConverter.cs#L1052).

**Comment by niksedk** [comment]
...it will execute in the order specified and can be multiple times
It used to be like that... would that be nice to have?

**Comment by Rouzax** [comment]
> ```
> ...it will execute in the order specified and can be multiple times
> ```
> 
> It used to be like that... would that be nice to have?

sometimes yes, but not really urgently 😄 
If I can do a Fix Common Errors first I will fix OCR errors, etc after I can clean up HI which in turn might lead to new Common Errors

**Comment by xylographe** [comment]
Two suggestions:

Add a new parameter `/transformations` (or a better name) with a short alias (e.g. `/tf`) that implements "_...it will execute in the order specified and can be multiple times_". For example `/tf:FixCommonErrors,RemoveTextForHI,FixCommonErrors`.

Keep the individual switches for users who don't want to be bothered figuring out the optimum order themselves. I think, the current order could be improved, perhaps, 
```
ReverseRtlStartEnd
FixCommonErrors
RemoveFormatting
RemoveTextForHI
ReDoCasing
```

**Comment by niksedk** [comment]
What would be the optimum order?

That's really hard to say.... RemoveFormatting is probably nice to have as one of the first, but as more actions are added determining the best order will be even harder. I'm not really sure that there is a best order and "Fix common errors" perhaps could be run in the beginning and the end.

(I should probably write a little on the help page)

**Comment by xylographe** [comment]
```
1. FixCommonErrors
2. RemoveFormatting
3. RemoveTextForHI
4. ReDoCasing
5. FixCommonErrors
```
Where would you put **ReverseRtlStartEnd**?
Very early (like before 1 or before 2)?
Or, near the end (before 5 or after 5)?

**Comment by xylographe** [comment]
The “_...it will execute in the order specified and can be multiple times_” behaviour  should be working correctly since commit b9310aed16a5312a9b4d86cd94b26b51b4067728.
