### ISSUE TITLE
"SubTitle Editor has stopped working" Issue

### ISSUE THREAD

**Issue by fasilmrm** [SubtitleEdit/subtitleedit#4173]
"SubTitle Editor has stopped working" Issue
whenever i try to add a subtitle or a video file, this error popup.. i tried 3.5.15, 3.5.14...
i'm on windows 10. Any solutions?
@niksedk 
 ![Subtitle Edit 5_9_2020 8_29_40 PM](https://user-images.githubusercontent.com/61681381/81479444-2f6f4f00-9234-11ea-9607-adc3b11e1b53.png)

**Comment by niksedk** [comment]
We probably need more information.

What version of SE are you using?
What OS are you using?
What were you doing?
How can we re-create it?
Could you attach a log?

**Comment by fasilmrm** [comment]
@niksedk 
- Using Windows 10
- I opened subtitle file and this error happened, also I tried to add video and the same happened
- i don't know how to take log..

**Comment by niksedk** [comment]
Try opening the `Event Viewer` and look in the "Application log".

Also, you might want to try to install latest .net framework 4.x from Microsoft: https://dotnet.microsoft.com/download/dotnet-framework

And do try switching the video player to "mpv" - Options -> Settings -> Video player - Click on "Download mpv lib".

**Comment by fasilmrm** [comment]
@niksedk 
.net is already installed

These are the errors from event log

1-Faulting application name: SubtitleEdit.exe, version: 3.5.15.0, time stamp: 0x5eabd875
Faulting module name: atiumd64.dll, version: 9.14.10.1128, time stamp: 0x563ac4aa
Exception code: 0xc0000005
2-Application: SubtitleEdit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at QuartzTypeLib.<c8a79e93-d9a5-4fb4-bad2-4b176956bcb6>IMediaControl.RenderFile(System.String)
   at Nikse.SubtitleEdit.Logic.VideoPlayers.QuartsPlayer.Initialize(System.Windows.Forms.Control, System.String, System.EventHandler, System.EventHandler)
   at Nikse.SubtitleEdit.Logic.UiUtil.InitializeVideoPlayerAndContainer(System.String, Nikse.SubtitleEdit.Core.VideoInfo, Nikse.SubtitleEdit.Controls.VideoPlayerContainer, System.EventHandler, System.EventHandler)
   at Nikse.SubtitleEdit.Forms.Main.OpenVideo(System.String)
   at Nikse.SubtitleEdit.Forms.Main.buttonOpenVideo_Click(System.Object, System.EventArgs)
   at Nikse.SubtitleEdit.Forms.Main.MediaPlayer_OnEmptyPlayerClicked(System.Object, System.EventArgs)
   at Nikse.SubtitleEdit.Controls.VideoPlayerContainer.PanelPlayerMouseDown(System.Object, System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.OnMouseDown(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseDown(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at Nikse.SubtitleEdit.Program.Main()

Any solution?

**Comment by niksedk** [comment]
@fasilmrm: ah, "QuartzTypeLib" is the directshow video player... some codecs on your machine.
Do try "mpv" as video player :)

**Comment by fasilmrm** [comment]
@niksedk i downloaded mpv like u said and still facing the issue..

**Comment by niksedk** [comment]
@fasilmrm: Could you upload the log again?

And you video player in SE is set to mpv?
![image](https://user-images.githubusercontent.com/1261331/81526240-5ffbd980-9357-11ea-8c5e-b17cfafea29b.png)

**Comment by fasilmrm** [comment]
@niksedk issue solved, my mistake bro. changed player to mpv
