### ISSUE TITLE
Unable to export FAB image script on 3.5.18.1 or 17.1 

### ISSUE THREAD

**Issue by rotorwave** [SubtitleEdit/subtitleedit#4569]
Following error occurs anytime I try to export to Adobe FAB Image Script. Installed on Windows 10 Pro version 2004 (os build 19041.630)
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 3.5.18.1. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
A generic error occurred in GDI+.

Stack Trace:
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)

   at Nikse.SubtitleEdit.Forms.ExportPngXml.WriteParagraph(Int32 width, StringBuilder sb, Int32 border, Int32 height, Int32 imagesSavedCount, VobSubWriter vobSubWriter, FileStream binarySubtitleFile, MakeBitmapParameter param, Int32 i)

   at Nikse.SubtitleEdit.Forms.ExportPngXml.ButtonExportClick(Object sender, EventArgs e)

   at System.Windows.Forms.Control.OnClick(EventArgs e)

   at System.Windows.Forms.Button.OnClick(EventArgs e)

   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ButtonBase.WndProc(Message& m)

   at System.Windows.Forms.Button.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by rotorwave** [comment]
I believe I found the issue: procmon indicated:
C:\Program Files\Subtitle Edit\IMAGE001.png access denied (once I alllowd it, the program worked fine)
Not sure why the program wants to store the images in the program files directory....

**Comment by niksedk** [comment]
Thx for the info :)

Should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.18/SubtitleEditBeta.zip
