### ISSUE TITLE
Visual Sync doesn't save window size

### ISSUE THREAD

**Issue by SuperDre** [SubtitleEdit/subtitleedit#4851]
Would be nice if the visual sync window would remember it's size, on a large screen the default is very small.
Steps to reproduce:
-Open Visual Sync
-Resize window
-Close Visual Sync
-Close subtitle edit
-Reopen Subtitle edit
-Open Visual Sync and it's back to it's small size.

**Comment by niksedk** [comment]
Fix in 6b127cb223af4c7b5de25fe864ffe4e8905e0ecb

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip

**Comment by SuperDre** [comment]
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 3.6.0.101. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Could not load file or assembly 'libse, Version=3.6.0.101, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Stack Trace:
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Resources.ResourceReader.FindType(Int32 typeIndex)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at Nikse.SubtitleEdit.Forms.VisualSync.InitializeComponent()
   at Nikse.SubtitleEdit.Forms.VisualSync..ctor()
   at Nikse.SubtitleEdit.Forms.Main.ShowVisualSync(Boolean onlySelectedLines)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by OmrSi** [comment]
@niksedk Seems to be an issue in the embedded resources. It only happens outside of Debug.

**Comment by niksedk** [comment]
Yes, a bit strange about working in debug mode... anyway, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.0/SubtitleEditBeta.zip
