### ISSUE TITLE
Failed to import mp4 video

### ISSUE THREAD

**Issue by weshouman** [SubtitleEdit/subtitleedit#4868]
When trying to import an `mp4` file, I get the message `you could also switch video player from "" to "mpv"` alongside with the following exception
```
Message: Class not registered

Class not registered
Stack Trace: 
at QuartzTypeLib.<aca00adc-ede2-4a59-b21b-9fa8b645312d>IMediaControl.RenderFile(String strFilename)
   at Nikse.SubtitleEdit.Logic.VideoPlayers.QuartsPlayer.Initialize(Control ownerControl, String videoFileName, EventHandler onVideoLoaded, EventHandler onVideoEnded)
   at Nikse.SubtitleEdit.Logic.UiUtil.InitializeVideoPlayerAndContainer(String fileName, VideoInfo videoInfo, VideoPlayerContainer videoPlayerContainer, EventHandler onVideoLoaded, EventHandler onVideoEnded)
```

**Comment by OmrSi** [comment]
Are you using DirectShow as your video player?
I so, either install LAVFilters, or switch to using MPV the video player.
