### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by TareqSh29** [SubtitleEdit/subtitleedit#5758]
Index was out of range. Must be non-negative and less than the size of  the collection.

Parameter name: index

Stack Trace:
at
System.ThrowHeIper.ThrowArgumentOutOfRangeException(Exception
Argument argument, ExceptionResource resource)
at system.Collections.Generic.List1.set_Item(Int32 index, T value)
at
NikseSubtitIeEdit.Forms.Main.AudioWaveform_OnTimeChanged(Objec t sender, ParagraphEventArgs e)
at
NikseSubtitleEdit.ControlsAudioVisualizer.WaveformMouseDown(Object sender, MouseEventArgs e)
at System.Windows.Forms.Control.WmMouse0own(MouseEventArgs e)

at system.Windows.Forms.ControI.WmMouseDown(Message& m, MouseButtons button,  Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.UserControl.WndProc(Message&  m)
at System.Windows.Forms.NativeWindow.CalIback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

**Comment by niksedk** [comment]
Hi @TareqSh29, can you re-create the error in latest beta? 
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip
