### ISSUE TITLE
Index out of Bounds Error When Removing Text for HI

### ISSUE THREAD

**Issue by MoonPie75** [SubtitleEdit/subtitleedit#6009]
I've run into several examples where I'm receiving the following error when attempting to auto-remove text for HI from SRT files. Error throws in both regular and batch mode.

I thought it might be something with the character encoding but I've tried resaving with ANSI, UTF-8, UTF-8 BOM, etc, etc without luck.  It occurs even if I pass the files through a text editor and generate a completely fresh file (so maybe it's not related to the encoding after all).

A copy of the error message and a .zip with two examples are attached. 

It's a very rare error (I've seen it maybe a dozen times in >20,000 files) so it's far, far more of a minor annoyance than a problem. Certainly not something for the priority list but I thought you'd like to know.

Thanks for all the excellent work!

Cheers!

*******
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 3.6.6.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Index was outside the bounds of the array.

Stack Trace:
   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.RemoveColon(String text)

   at Nikse.SubtitleEdit.Core.Forms.RemoveTextForHI.RemoveTextFromHearImpaired(String inputWithoutUnicodeReplace, Subtitle subtitle, Int32 index)

   at Nikse.SubtitleEdit.Forms.FormRemoveTextForHearImpaired.GeneratePreview()

   at Nikse.SubtitleEdit.Forms.Main.RemoveTextForHearImpairedToolStripMenuItemClick(Object sender, EventArgs e)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*******

[Example_Files.zip](https://github.com/SubtitleEdit/subtitleedit/files/8839370/Example_Files.zip)

**Comment by niksedk** [comment]
Thx for the info + files :)

I think this has been reported and few times and should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.6/SubtitleEditBeta.zip
(The two test files works fine for me in current beta)

**Comment by MoonPie75** [comment]
Sorry. I searched for it but in the context of text for HI removal. Must have missed it.

Can confirm that 3.6.6 beta 27 fixes the issue.

Thanks again.
