### ISSUE TITLE
SE 3.6.8.125, whisper, linux and python-ffmpeg

### ISSUE THREAD

**Issue by hendrack** [SubtitleEdit/subtitleedit#6433]
When trying to use whisper, I get an exception and this code in the console:

`Calling whisper with : whisper --language "en" --model "small.en"  "/tmp/1af84c3c-bff1-4655-a141-fc8035b8ce6c.wav"
Wav file name: /tmp/1af84c3c-bff1-4655-a141-fc8035b8ce6c.wavAttributeError: module 'ffmpeg' has no attribute 'Error'

except ffmpeg.Error as e:

File "/home/chris/.local/lib/python3.9/site-packages/whisper/audio.py", line 46, in load_audio

audio = load_audio(audio)

File "/home/chris/.local/lib/python3.9/site-packages/whisper/audio.py", line 111, in log_mel_spectrogram

mel = log_mel_spectrogram(audio)

File "/home/chris/.local/lib/python3.9/site-packages/whisper/transcribe.py", line 76, in transcribe

result = transcribe(model, audio_path, temperature=temperature, **args)

File "/home/chris/.local/lib/python3.9/site-packages/whisper/transcribe.py", line 275, in cli

sys.exit(cli())

File "/home/chris/.local/bin/whisper", line 8, in <module>

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

AttributeError: module 'ffmpeg' has no attribute 'input'

ffmpeg.input(file, threads=0)

File "/home/chris/.local/lib/python3.9/site-packages/whisper/audio.py", line 42, in load_audio

Traceback (most recent call last):
Calling whisper done in 00:00:07.3034833`

![2022-11-19_12-05](https://user-images.githubusercontent.com/23265970/202847856-0b40e976-028c-4ef6-814e-aa3140c1d6d8.png)

**Comment by hendrack** [comment]
This is related to this python ffmpeg issue: https://github.com/kkroening/ffmpeg-python/issues/174.
