### ISSUE TITLE
Another suggestion for "Audio to text" with Whisper

### ISSUE THREAD

**Issue by oep42** [SubtitleEdit/subtitleedit#6598]
The results of "Audio to text" with Whisper, are textually impressive with Subtitle Edit 3.6.10 NEXT beta 219, but the synchronisation between spoken words and subtitles, is not as good as it should be. The repository called "WhisperX" at "https://github.com/m-bain/whisperX", seems to be an addition to Whisper that significantly improves this synchronisation. Is it possible to add "WhisperX" to Subtitle Edit's "Audio to text" with Whisper? If so, I would suggest to add this.

**Comment by niksedk** [comment]
I've testing it a bit... and I just do not get good results with WhisperX. I get repeated lines (with both base and medium models)
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip

So, I will remove this again as a UI setting.

**Comment by oep42** [comment]
Thanks for looking into this. I am curious to compare the result of transcribing with WhisperX, with the result of transcribing without WhisperX. (I assume that with WhisperX, the subtitles are better synchronized with the spoken words, than without WhisperX.) For this, I used SubtitleEdit 3.6.10 BETA 260.

I would like to find out by testing, what the answer is to this question: Which is less work to improve manually afterwards: the output when transcribing with WhisperX, or the output when transcribing without WhisperX? (In other words, perhaps a little simplified: Which is less work to improve manually afterwards: repeated lines, or unsynchronized subtitles?)

In the dialog box "Audio to text (Whisper)", I found a right-click option for WhisperX, which, when chosen, results in the gray text "WhisperX" in that dialog box. Because of this, I supposed that WisperX would be available in SubtitleEdit 3.6.10 BETA 260. When I tried to transcribe a video after choosing WhisperX, I got an error message. See below for this error message. Because of this error message, I suppose that WhisperX has already been removed from SE.

Is there a beta version of SE available, that does include WhisperX? (I would love to test SE with WhisperX, and compare it with 'standard' Whisper.)

This is the error message:
===========================
An application error occurred in Subtitle Edit 3.6.10.260 - Microsoft Windows NT 6.3.9600.0.
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
The system cannot find the file specified

Stack Trace:
	at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startlnfo)
	at Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.GetWhisperProcess(String waveFileName, String model, String language, Boolean translate, DataReceivedEventHandler dataReceivedHandler)
	at Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.TranscribeViaWhisper(String waveFileName)
	at Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.GenerateBatch()
	at Nikse.SubtitleEdit.Forms.AudioToText.WhisperAudioToText.Button Generate_Click(Object sender, EventArgs e)
	at System.Windows.Forms.Control.OnClick(EventArgs e)
	at System.Windows.Forms.Button.OnClick(EventArgs e)
	at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
	at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
	at System.Windows.Forms.Control.WndProc(Message& m)
	at System.Windows.Forms.ButtonBase.WndProc(Message& m)
	at System.Windows.Forms.Button.WndProc(Message& m)
	at System.Windows.Forms.NativeWindow.Caliback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr Iparam)

**Comment by niksedk** [comment]
I've removed WhisperX again... as it gave so poor results.

**Comment by oep42** [comment]
Too bad that WhisperX did not improve things. Let's hope Whisper's timestamps will improve in the future.

**Comment by Burseblades** [comment]
oep42: The error you posted is identical to the one I received. I'm not a coder but I can follow a "cook book" and I thought I had followed everything precisely. Disappointed.
