### ISSUE TITLE
Video engine disabled and mpv not downloading

### ISSUE THREAD

**Issue by JAK1234567** [SubtitleEdit/subtitleedit#6600]
![error in subtitle edit](https://user-images.githubusercontent.com/122858380/212832622-845620c3-9866-44b2-9799-b4a3be50caac.PNG)
![mpv not downloading](https://user-images.githubusercontent.com/122858380/212832655-5ca14bbe-2744-4ab4-8ce8-fdfc4006b758.PNG)

**Comment by niksedk** [comment]
Could you try latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.10/SubtitleEditBeta.zip ?

And you are on Win10 64-bit?
Do you have a firewall installed or in some country that might block some internet addresses?

You can try to re-install dotnet framework 4.8...
Also, check file `error_log.txt` in the SE data folder (press ctrl+alt+shift+d in the SE main window to open the SE data folder).

**Comment by JAK1234567** [comment]
This is the error_log
-----------------------------------------------------------------------------
Date: 01/18/2023 18:00:04
SE: 3.6.10.238 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: DownloadAsync failed

System.Net.Http.HttpRequestException
Message: An error occurred while sending the request.
StackTrace:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()
System.Net.WebException
Message: Unable to connect to the remote server
StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
System.Net.Sockets.SocketException
Message: No connection could be made because the target machine actively refused it 49.44.79.236:443
StackTrace:    at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
-----------------------------------------------------------------------------
Date: 01/18/2023 18:00:25
SE: 3.6.10.238 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: InitializeVideoPlayerAndContainer failed to load video player

System.Runtime.InteropServices.COMException
Message: Class not registered

Class not registered

StackTrace:    at QuartzTypeLib.IMediaControl.RenderFile(String strFilename)
   at Nikse.SubtitleEdit.Logic.VideoPlayers.QuartsPlayer.Initialize(Control ownerControl, String videoFileName, EventHandler onVideoLoaded, EventHandler onVideoEnded)
   at Nikse.SubtitleEdit.Logic.UiUtil.DoInitializeVideoPlayer(String fileName, VideoInfo videoInfo, VideoPlayerContainer videoPlayerContainer, EventHandler onVideoLoaded, EventHandler onVideoEnded)
   at Nikse.SubtitleEdit.Logic.UiUtil.InitializeVideoPlayerAndContainer(String fileName, VideoInfo videoInfo, VideoPlayerContainer videoPlayerContainer, EventHandler onVideoLoaded, EventHandler onVideoEnded)
-----------------------------------------------------------------------------
Date: 01/18/2023 18:00:56
SE: 3.6.10.238 - Microsoft Windows NT 10.0.19045.0 - 64-bit
Message: DownloadAsync failed

System.Threading.Tasks.TaskCanceledException
Message: A task was canceled.
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Core.Common.HttpClientHelper.<DownloadAsync>d__2.MoveNext()


Cann't get the head or tail of it.

**Comment by niksedk** [comment]
Did you try to re-install the dotnet 4.8 framework?
Did you have a firewall / proxy / some-other-blocking-software ?
Are you in a country that blocks some internet traffic?

You can download libmpv2-64.zip manually from here: https://github.com/SubtitleEdit/support-files/tree/master/mpv
(unpack to your SE data folder)
