### ISSUE TITLE
Microsoft Translate API Problem

### ISSUE THREAD

**Issue by kawsarahmed072096** [SubtitleEdit/subtitleedit#7410]
Dear Sir, when i install microsoft translate api then when i go to translate this problem is showing pls solve.
![Screenshot_1](https://github.com/SubtitleEdit/subtitleedit/assets/98688188/618fe231-9dc9-43e9-9dd3-d64da31e2ad9)

**Comment by polysyllabik** [comment]
I got the same error here. 

Have double-checked my key and token endpoint. Doesn't look like they are the causes. I looked it up in Microsoft's document, and selected the endpoint which is supposed to be correct:

"https://<your-region>.api.cognitive.microsoft.com/sts/v1.0/issueToken"



---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 4.0.1.0 - 64-bit  - Microsoft Windows NT 10.0.19045.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Parse error: expected ','.

Stack Trace:
   at Nikse.SubtitleEdit.Core.Common.JsonParser.Expect(Char c)

   at Nikse.SubtitleEdit.Core.Common.JsonParser.Dictionary()

   at Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)

   at Nikse.SubtitleEdit.Core.Translate.Service.MicrosoftTranslationService.FillTranslationPairsFromJson(String json)

   at Nikse.SubtitleEdit.Core.Translate.Service.MicrosoftTranslationService.GetTranslationPairs()

   at Nikse.SubtitleEdit.Forms.Translate.GenericTranslate.SetupLanguageSettings()

   at Nikse.SubtitleEdit.Forms.Translate.GenericTranslate.comboBoxTranslationServices_SelectedIndexChanged(Object sender, EventArgs e)

   at Nikse.SubtitleEdit.Controls.NikseComboBox.set_SelectedIndex(Int32 value)

   at Nikse.SubtitleEdit.Forms.Translate.GenericTranslate.AddTranslationService(ITranslationService translationService)

   at Nikse.SubtitleEdit.Forms.Translate.GenericTranslate.InitTranslationServices()

   at Nikse.SubtitleEdit.Forms.Translate.GenericTranslate.Initialize(Subtitle subtitle, Subtitle target, String title, Encoding encoding, SubtitleFormat subtitleFormat)

   at Nikse.SubtitleEdit.Forms.Main.Translate(Boolean onlySelectedLines)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by niksedk** [comment]
This should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.1/SubtitleEditBeta.zip
