### ISSUE TITLE
Unable to download (MPV + Ffmpeg)

### ISSUE THREAD

**Issue by GreyPerson2** [SubtitleEdit/subtitleedit#7842]
I hope there is a manual ways to add these stuff, because my internet is still fine and can download both of these file, but cant use it.
**Ffmpeg**
```
Unable to download https://github.com/SubtitleEdit/support-files/releases/download/ffmpeg-v6-1/ffmpeg61.zip!

No content downloaded - missing file or no internet connection!

   at Nikse.SubtitleEdit.Forms.DownloadFfmpeg.CompleteDownload(MemoryStream downloadStream)
   at Nikse.SubtitleEdit.Forms.DownloadFfmpeg.DownloadFfmpeg_Shown(Object sender, EventArgs e)

```
**MPV**
```
Unable to download https://github.com/SubtitleEdit/support-files/releases/download/ibmpv-2023-11-26/libmpv2-64.zip!

No content downloaded - missing file or no internet connection!

   at Nikse.SubtitleEdit.Forms.Options.SettingsMpv.CompleteDownload(MemoryStream downloadStream)
   at Nikse.SubtitleEdit.Forms.Options.SettingsMpv.ButtonDownloadClick(Object sender, EventArgs e)
```

**Comment by GreyPerson2** [comment]
I fixed it now.
I was reading back at this https://www.nikse.dk/subtitleedit/help#settings_video
(Press Ctrl + Shift + Alt + D)
And it open windows, i was thought were it instal so.... I just need copy and paste the file (MPV-FFMPEG) to that and it done.
Sorry if this bothering.
