### ISSUE TITLE
Request for Subtitle-to-Speech Feature Integration in SE

### ISSUE THREAD

**Issue by msjsc001** [SubtitleEdit/subtitleedit#8011]
![image](https://github.com/SubtitleEdit/subtitleedit/assets/93178788/9cc5031d-3b98-4c83-b8e5-75b27d1cdb6c)

Dear SE Developers,

I am a fan of SE and use it frequently for subtitle recognition and translation in my course videos. It has been a tremendous help to me.

I was wondering if SE could incorporate a feature to convert subtitles into speech, making educational videos more engaging. I have discovered numerous open-source speech models on the Hugging Face Models page (https://huggingface.co/models?sort=trending), but as a programming novice, I am unsure how to implement these models for subtitle dubbing. Specifically, I am interested in integrating Text-to-Speech and Text-to-Audio models into SE.

Thank you for considering my request. I look forward to any potential updates or guidance on this matter.

Best regards,

msjsc001

**Comment by niksedk** [comment]
MS has some built-in robot voice which are fast to generate.

I've tried https://github.com/neonbjb/tortoise-tts
It takes about 5 minutes for each line, but much better quality...

I guess most people want the human like voices?

**Comment by niksedk** [comment]
Hm, pyinstaller and  https://github.com/neonbjb/tortoise-tts is not that easy.
It get this error? Any hints? @Purfview  ?

````
C:\Users\nikse\AppData\Local\Programs\Python\Python310\Lib\site-packages\tortoise\dist>do_tts --output_path "C:\data" --preset ultra_fast --voice geralt --text="Hello, how are you today?"
Traceback (most recent call last):
  File "do_tts.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "api.py", line 23, in <module>
    from tortoise.utils.tokenizer import VoiceBpeTokenizer
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\tokenizer.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "inflect\__init__.py", line 2041, in <module>
  File "inflect\__init__.py", line 2063, in engine
  File "typeguard\_decorators.py", line 223, in typechecked
  File "typeguard\_decorators.py", line 71, in instrument
  File "inspect.py", line 1139, in getsource
  File "inspect.py", line 1121, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code
[27488] Failed to execute script 'do_tts' due to unhandled exception!
````

**Comment by Purfview** [comment]
Did it work in Python? Look what is going on in ->`File "inspect.py", line 958, in findsource`.

**Comment by Purfview** [comment]
Did you got GPU with CUDA?

From that repo:
"If you want to use this on your own computer, you must have an NVIDIA GPU."

**Comment by niksedk** [comment]
I do not have nVidia GPU, but it works when calling with Python

**Comment by darnn** [comment]
Two things: It's "speech" rather than "speach", and, once you start the process, at least with the MS engine, there's no way to stop it. I thought it would only do it to the selected subtitle, it ended up trying to do it for the whole file and I had to kill the task to get it to stop.

**Comment by darnn** [comment]
Also, once I did let it finish with a short file, I got errors, both with "add audio to video file" checked and unchecked:

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/eaa46b05-fee3-4e85-aaa7-ea89ad665f0d)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/a411dd88-e664-4ef1-ba0f-9c84213b3029)

**Comment by niksedk** [comment]
@darnn: thx for testing :)

Any better in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip ?
Also, what engine are you using? Piper is probably the one to use....

**Comment by darnn** [comment]
I'm just using Microsoft in the moment, both since it's the fastest and since it has Hebrew (though I've been trying with English so far). Still getting this:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/d5cee7b8-f9cd-4c2f-b2d9-10cd2e6f3f7e)

**Comment by darnn** [comment]
Also, when I click `Test voice`, it generates the wav file, but doesn't play it in SE.

**Comment by niksedk** [comment]
@darnn: thx for testing :)
Hopefully better here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SubtitleEditBeta.zip ?

**Comment by darnn** [comment]
All the previous issues seem to have been resolved. The one thing I've noticed is that if you spam the `Test voice` button using the settings in the screenshot, you will eventually (after about five times for me) get this error:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/19672444/8c9a0d8f-4088-4f9d-84d2-6262084bf333)

And I do think it would be good to have a cancel (or interrupt, or whatever) button - when I first tried it, I had a two and a half hour video file open, and i had to wait for it to finish writing a wav file that long.

**Comment by niksedk** [comment]
TTS updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip

It's in the video menu now:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/1c1b1b44-f71a-4893-bf17-df8376e2cda8)

With ASSA, you can setup different voice for different actors:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/041a18b9-bb96-476b-9fef-492206517716)

More engines:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/d19f86c6-9156-467b-8a53-d0f213522670)

Non-ASSA mode:
![image](https://github.com/SubtitleEdit/subtitleedit/assets/1261331/11ac5d91-001d-40f2-bd2f-46e46fb0f8be)

**Comment by darnn** [comment]
Couple of things, both in non-ASSA mode:
1. The voice selection dropdown for Piper doesn't have a scroll bar, so you can't go lower than what you see on screen (I mean, you can, but you can't see what you're doing).
2. When attempting to use Coqui without setting up the server, SE gives the following error:
An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Tts.TextToSpeech.<GenerateParagraphAudioCoqui>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Tts.TextToSpeech.<GenerateParagraphAudio>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Tts.TextToSpeech.<buttonTestVoice_Click>d__33.MoveNext()
