### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by giogio33** [SubtitleEdit/subtitleedit#8384]
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 4.0.4.0 - 64-bit  - Microsoft Windows NT 10.0.19045.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Nikse.SubtitleEdit.Logic.VideoPlayers.QuartsPlayer.Pause()

   at Nikse.SubtitleEdit.Controls.VideoPlayerContainer.Pause()

   at Nikse.SubtitleEdit.Controls.VideoPlayerContainer.PauseAndDisposePlayer()

   at Nikse.SubtitleEdit.Forms.Main.FormMain_FormClosing(Object sender, FormClosingEventArgs e)

   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)

   at System.Windows.Forms.Form.WmClose(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by niksedk** [comment]
Should hopefully be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.5/SubtitleEditBeta.zip
Not that DirectShow will need something installed on your machine, like lav filters: https://github.com/Nevcairiel/LAVFilters/releases

But... SE works much better with mpv.
