### ISSUE TITLE
Auto-translate Error

### ISSUE THREAD

**Issue by soscaster** [SubtitleEdit/subtitleedit#8459]
I got this error when trying to use Auto-translate:
```
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 4.0.6.0 - 64-bit  - Microsoft Windows NT 10.0.19045.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Unable to cast object of type 'System.String' to type 'Nikse.SubtitleEdit.Core.Translate.TranslationPair'.

Stack Trace:
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.SelectLanguageCode(NikseComboBox comboBox, String languageIsoCode)

   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.SetupLanguageSettings()

   at Nikse.SubtitleEdit.Controls.NikseComboBox.NotifyTextChanged()

   at Nikse.SubtitleEdit.Controls.NikseComboBox.set_SelectedIndex(Int32 value)

   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.InitializeAutoTranslatorEngines()

   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate..ctor(Subtitle subtitle, Subtitle targetLines, String title, Encoding encoding)

   at Nikse.SubtitleEdit.Forms.Main.MakeAutoTranslate(Boolean onlySelectedLines)

   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)

   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)

   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)

   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)

   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ToolStrip.WndProc(Message& m)

   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by niksedk** [comment]
How can I re-create this?

**Comment by soscaster** [comment]
Not too much sure, but the Auto-translate still works on 4.0.5. I set the translate API key for DeepL, but when upgrading from 4.0.5 to 4.0.6, the error occurs. The only way that I can avoid the error is Reset all preferences, save it and then input the API key again, after that Auto-translate is working again.

**Comment by pangzheng** [comment]
4.0.6 版本问题一样，必须重置设置
