### ISSUE TITLE
Extract MPEG-TS DVB Subtitle Tracks using "Batch Convert" or Command Line

### ISSUE THREAD

**Issue by MounaLafi** [SubtitleEdit/subtitleedit#8470]
I used to extract MPEG-TS DVB Subtitle Tracks using SE Ver. 3.5.11 Beta5.

For a long time now, I didn't require to do bulk extract.

However, when I tried latest SE Ver. 4.0.6 I couldn't extract MPEG-TS DVB Subtitle Tracks in both GUI or Command Line.

In GUI, after selecting "Batch Convert", the resulting SUP files are with zero bytes in size.

I'm guessing, but could be wrong, that SE is trying to OCR the files though I've clearly selected the output to be "Blu-ray sup".

In Command Line, I'm getting the below error message:

ERROR: Object reference not set to an instance of an object.
   at Nikse.SubtitleEdit.Forms.ExportPngXml.MakeMakeBitmapParameter(Int32 index, Int32 screenWidth, Int32 screenHeight)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.TsToBluRaySup.WriteTrack(String fileName, String outputFolder, Boolean overwrite, Int32 count, StreamWriter stdOutWriter, BatchConvertProgress progressCallback, Nullable`1 resolution, ProgramMapTableParser programMapTableParser, Int32 pid, TransportStreamParser tsParser)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.TsConvert.ConvertFromTs(String targetFormat, String fileName, String outputFolder, Boolean overwrite, Int32& count, Int32& converted, Int32& errors, List`1 formats, StreamWriter stdOutWriter, BatchConvertProgress progressCallback, Nullable`1 resolution, TextEncoding targetEncoding, List`1 actions, TimeSpan offset, String deleteContains, Int32 pacCodePage, Nullable`1 targetFrameRate, HashSet`1 multipleReplaceImportFiles, String ocrEngine, Boolean teletextOnly, String teletextOnlyPage)
   at Nikse.SubtitleEdit.Logic.CommandLineConvert.CommandLineConverter.Convert(String[] arguments)

Also, it is only extracting one subtitle track.

I went back to SE Ver. 3.5.11 Beta5 and it is still working in both GUI and Command Line. 

And it is extracting all subtitle tracks.

Please also refer to this closed [issue](https://github.com/SubtitleEdit/subtitleedit/issues/3633). for reference.

**Comment by niksedk** [comment]
I've tried to fix the issue here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.6/SubtitleEditBeta.zip
Let me know how it works for you now :)

**Comment by MounaLafi** [comment]
Thanks Nikse for prompt response.
I've tested this Beta version with both GUI & CLI and it is working perfectly and all Subtitle Tracks are being extracted.
Appreciated your kind efforts.
