### ISSUE TITLE
Unsupported model binary version

### ISSUE THREAD

**Issue by DavidWilliam11** [SubtitleEdit/subtitleedit#8471]
I'm try to use a custom model, and the log said:
Standalone Faster-Whisper r192.3 running on: CPU

RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v67324752. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)

File "faster_whisper\transcribe.py", line 140, in __init__

File "D:\whisper-fast\__main__.py", line 1431, in cli

File "D:\whisper-fast\__main__.py", line 1600, in <module>

Traceback (most recent call last):

[8664] Failed to execute script '__main__' due to unhandled exception!
Calling whisper Purfview's Faster-Whisper done in 00:00:04.0967843
Loading result from STDOUT

**Comment by niksedk** [comment]
You can try Purfview Faster Whisper XXL... 
This is an issue regarding Faseter Whisper - please report here: https://github.com/Purfview/whisper-standalone-win/issues
