### ISSUE TITLE
Input string was not in correct format: trying to use Auto-Translate with ChatGPT

### ISSUE THREAD

**Issue by nyck33** [SubtitleEdit/subtitleedit#8506]
```bash
Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Nikse.SubtitleEdit.Core.AutoTranslate.ChatGptTranslate.<Translate>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
```
![image](https://github.com/SubtitleEdit/subtitleedit/assets/25189545/3d010f6b-2183-4bcd-9d4b-70e852e5fb23)

![image](https://github.com/SubtitleEdit/subtitleedit/assets/25189545/d4b2c3ac-f83c-4e21-9a9b-bcb7d6e459fb)

The prompt:
```bash
system_prompt: You are an experienced semantic translator. Follow the instructions carefully.,
user_prompt: Translate this text from Japanese to English. The text is from an Edo period drama called 「暴れん坊将軍II」. Please ensure the translation retains the historical context and nuances of the Edo period language. Interleave the \"|\" segment separator in the response. If possible use these parameters: {temperature=temperature, top_p=1.0, frequency_penalty=0.0, presence_penalty=0.0}.  ALWAYS return the SAME number of segments. NEVER skip any segment. NEVER combine segments.\n\n
```

**Comment by niksedk** [comment]
SE does not allow the curly brackets in the prompt. 
Also, make sure no comments or intro are added by the AI.
Only add one prompt.
