### ISSUE TITLE
ChatGPT Error

### ISSUE THREAD

**Issue by NightWalker77V** [SubtitleEdit/subtitleedit#8591]
Hi there, I'm getting this error when I want to use Auto-translation:

No connection could be made because the target machine actively refused it 127.0.0.1:1234
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

**Comment by niksedk** [comment]
What url are you using? Do you have a local ChatGPT clone?
Please add a few screenshots?

Using ChatGPT and translate you should use `https://api.openai.com/v1/chat/completions/` and a valid API key.

**Comment by Giveyouhell88** [comment]
Hi niksedk, I use my GPT API key for Auto-translate, but it shows this message after I click Auto-Translate.
Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Nikse.SubtitleEdit.Core.AutoTranslate.ChatGptTranslate.<Translate>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
{
    "error": {
        "message": "The model `gpt-4o` does not exist or you do not have access to it.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by niksedk** [comment]
`gpt-40` works fine here
