### ISSUE TITLE
ERRO while, Auto-Translation: ChatGpt API

### ISSUE THREAD

**Issue by addamss** [SubtitleEdit/subtitleedit#8657]
Can u help me with this error while trying translate with chatgpt API?
![Cap](https://github.com/user-attachments/assets/792f5a47-47df-45ac-8999-357c277f9fb7)

**Comment by niksedk** [comment]
Please supply the whole error text... you can copy-paste the error text.

**Comment by addamss** [comment]
Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Nikse.SubtitleEdit.Core.AutoTranslate.ChatGptTranslate.<Translate>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
{
  "error": {
    "message": "You must provide the 'OpenAI-Beta' header to access the Assistants API. Please try again by setting the header 'OpenAI-Beta: assistants=v2'.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_beta"
  }
}

**Comment by niksedk** [comment]
It works fine here... what model are you using?
