### ISSUE TITLE
RuntimeError: Unsupported Model Binary Version With Purfview's Faster-Whisper

### ISSUE THREAD

**Issue by onlinepersonprivate** [SubtitleEdit/subtitleedit#8678]
Version: 4.0.7
GPU: RTX 3050Ti Notebook GPU
Installed Python Version: 3.12.4
The below error occurred with multiple different versions of both Faster-Whisper and Faster-Whisper XXL standalone releases and with multiple different models.

```
Date: 07/27/2024 00:32:47
SE: 4.0.7.0 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (Purfview's Faster-Whisper) with : C:\Users\[username]\AppData\Roaming\Subtitle Edit\Whisper\Purfview-Whisper-Faster\whisper-faster.exe --language en --model "medium.en"  "C:\Users\[username]\AppData\Local\Temp\f47598e5-cfd7-4a7e-b690-e337f7732dce.wav"
[14832] Failed to execute script '__main__' due to unhandled exception!

Standalone Faster-Whisper r192.3 running on: CUDA

RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v1868833084. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)

File "faster_whisper\transcribe.py", line 140, in __init__

File "D:\whisper-fast\__main__.py", line 1431, in cli

File "D:\whisper-fast\__main__.py", line 1600, in <module>

Traceback (most recent call last):
Calling whisper Purfview's Faster-Whisper done in 00:00:02.7297234
Loading result from STDOUT
```

**Comment by niksedk** [comment]
I just tried a blank SE 4.0.7 installation... download the 1.5 GB medium en model + faster whisper... and it works fine here.
I cannot re-produce your error, sorry.

**Comment by Purfview** [comment]
Maybe download failed, delete the model folder and download it again.
