### ISSUE TITLE
Subtitle edit error I'm using the latest version

### ISSUE THREAD

**Issue by PepsiMan2024-webdebug** [SubtitleEdit/subtitleedit#8745]
![Untitled](https://github.com/user-attachments/assets/eb377239-b43f-4b7f-9ba0-796c6aa03574)
my subtitle edit on 32 bit win 7 is giving this error I know that's a repeated question is there a bug in the app
for any one that doesn't see the text box error i also copied the dialog box error for you I got this from thiojoe
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 4.0.7.0 - 32-bit  - Microsoft Windows NT 6.1.7601 Service Pack 1. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
The specified executable is not a valid application for this OS platform.

Stack Trace:
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)

   at System.Diagnostics.Process.Start()

   at Nikse.SubtitleEdit.Forms.AddWaveform.buttonRipWave_Click(Object sender, EventArgs e)

   at Nikse.SubtitleEdit.Forms.AddWaveform.AddWaveform_Shown(Object sender, EventArgs e)

   at System.Windows.Forms.Form.OnShown(EventArgs e)

   at System.Windows.Forms.Form.CallShownEvent()

   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by PepsiMan2024-webdebug** [comment]
>---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 4.0.7.0 - 32-bit  - Microsoft Windows NT 6.1.7601 Service Pack 1. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
The specified executable is not a valid application for this OS platform.

Stack Trace:
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)

   at System.Diagnostics.Process.Start()

   at Nikse.SubtitleEdit.Forms.AddWaveform.buttonRipWave_Click(Object sender, EventArgs e)

   at Nikse.SubtitleEdit.Forms.AddWaveform.AddWaveform_Shown(Object sender, EventArgs e)

   at System.Windows.Forms.Form.OnShown(EventArgs e)

   at System.Windows.Forms.Form.CallShownEvent()

   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by niksedk** [comment]
You need to use a 32-bit version of ffmpeg that can run on your system.
Or likewise vlc.
Or upgrade to a newer 64-bit OS.

**Comment by PepsiMan2024-webdebug** [comment]
does it work with wmv

**Comment by PepsiMan2024-webdebug** [comment]
windows media player
