### ISSUE TITLE
Piper error when trying to run Piper TTS

### ISSUE THREAD

**Issue by Gaffers2277** [SubtitleEdit/subtitleedit#8762]
When i click test voice or generate speech from text it throws this error.

An error occurred while trying to generate speech.

Could not find file 'C:\Users\alexg\AppData\Roaming\Subtitle Edit\TextToSpeech\Piper\out.wav'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Nikse.SubtitleEdit.Forms.Tts.TextToSpeech.GenerateParagraphAudioPiperTts(Subtitle subtitle, Boolean showProgressBar, String overrideFileName)
   at Nikse.SubtitleEdit.Forms.Tts.TextToSpeech.buttonTestVoice_Click(Object sender, EventArgs e)

**Comment by Gaffers2277** [comment]
So, i came back to the program today and reopened it and now its working. For any one else in the future just close and reopen the program and that should fix this.
