### ISSUE TITLE
Windows Forms Thread Exception

### ISSUE THREAD

**Issue by DVZs79** [SubtitleEdit/subtitleedit#8789]
Not sure, if this has been reported or not.
---------------------------
Windows Forms Thread Exception
---------------------------
An application error occurred in Subtitle Edit 4.0.4.0 - 64-bit  - Microsoft Windows NT 10.0.19045.0. 
Please report at https://github.com/SubtitleEdit/subtitleedit/issues with the following information:

Error Message:
Index was outside the bounds of the array.

Stack Trace:
   at Nikse.SubtitleEdit.Core.Forms.FixCommonErrors.FixMissingOpenBracket.RestoreMissingOpenParenthesis(String input)
   at Nikse.SubtitleEdit.Core.Forms.FixCommonErrors.FixMissingOpenBracket.Fix(Subtitle subtitle, IFixCallbacks callbacks)
   at Nikse.SubtitleEdit.Forms.FixCommonErrors.RunSelectedActions()
   at Nikse.SubtitleEdit.Forms.FixCommonErrors.Next()
   at Nikse.SubtitleEdit.Forms.FixCommonErrors.ButtonFixClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by niksedk** [comment]
Not to sure either... could you attach or email the subtitle file?

**Comment by niksedk** [comment]
Ah, attachments need to be made here on Gtihub (drag-n-drop as .zip or .txt file)
(email attachments are not added)
