### ISSUE TITLE
google translate api v2 not working

### ISSUE THREAD

**Issue by Gibsoniste** [SubtitleEdit/subtitleedit#8822]
I've created my API key, billing is enabled, I have verified the key, but for some reason i still get this issue.

It says the API key isn't valid, but it is perfectly valid. Am I doing something wrong?

"Perhaps billing is not enabled (or API key is invalid)?"
   at Nikse.SubtitleEdit.Core.AutoTranslate.GoogleTranslateV2.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
{
  "error": {
    "code": 403,
    "message": "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.",
    "errors": [
      {
        "message": "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

**Comment by niksedk** [comment]
Try reading this: https://github.com/SubtitleEdit/subtitleedit/discussions/6773#discussioncomment-5417761
