### ISSUE TITLE
Auto-translate - Thread Exception

### ISSUE THREAD

**Issue by andwan0** [SubtitleEdit/subtitleedit#8837]
On my Mint Linux I can run Subtitle Edit via Mono with no problems.
Now running on SteamDeck (ArchLinux). When I goto Auto-translate it gives me:

Windows Forms Thread Exception
An application error occurred in Subtitle Edit 4.0.8.0 - 64-bit - Microsoft Windows NT 10.0.18362.0.

Error Message:
Object reference not set to an instance of an object

Stack Trace:
  at System.Windows.Forms.InputLanguage.get_LayoutName()
  at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.EvaluateDefaultTargetLanguageCode(System.String defaultSourceLanguage)
  at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.SetupLanguageSettings()
  at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.nikseComboBoxEngine_SelectedIndexChanged(System.Object sender, System.EventArts e)
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c
  at System.Reflection.RuntimeMethodInfo.InternalInvoke
  at System.Reflection.RuntimeMethodInfo.Invoke

:0

https://imgur.com/a/9oEFFMe
![Screenshot_20240918_191933](https://github.com/user-attachments/assets/a5650a48-3672-4ea2-8e88-db80ea320a73)

**Comment by tkcofa** [comment]
I have a similar problem
[Ashampoo_Snap_Tuesday, October 15, 2024_10h44m10s.pdf](https://github.com/user-attachments/files/17375436/Ashampoo_Snap_Tuesday.October.15.2024_10h44m10s.pdf)

**Comment by andwan0** [comment]
I figured it out. We need to install dotNet runtime in our wine prefix (virtual environment). Just use Winetricks.
