### ISSUE TITLE
DEEPLX error

### ISSUE THREAD

**Issue by techguru0** [SubtitleEdit/subtitleedit#8914]
not sure what it means

Forbidden! 

   at Nikse.SubtitleEdit.Core.AutoTranslate.DeepLXTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()

**Comment by niksedk** [comment]
Could you try latest beta version?
https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.8/SubtitleEditBeta.zip

You need to start Docker and run `docker run -itd -p 1188:1188 ghcr.io/owo-network/deeplx:latest` before translating with DeepLX

**Comment by techguru0** [comment]
> Docker

on windows?

**Comment by niksedk** [comment]
> > Docker
> 
> on windows?

Yes, https://docs.docker.com/desktop/install/windows-install/

I use it almost every day :)

**Comment by niksedk** [comment]
Could you make it work?
