### ISSUE TITLE
ChatGPT | Automatic Translation

### ISSUE THREAD

**Issue by Hayholten** [SubtitleEdit/subtitleedit#9011]
Hi, everyone,

I'm reopening a topic already discussed in other tickets concerning the bug that blocks automatic translation by ChatGPT.

I'm using the portable version 4.0.8 of Subtitle Edit and I have a paid account with ChatGPT. Here's a screenshot of the problem:

![386285041-c954e511-e8b4-4ca8-a940-78eafe5c6fbf](https://github.com/user-attachments/assets/5e602574-df84-4752-afed-7b43bd2581b2)

Thanks in advance for your help ;)

**Comment by Hayholten** [comment]
Any clue on this friends ?

**Comment by bwvanlith** [comment]
Same here after switching to 4.08 after fresh win 11 install. No changes at Chatgpt side for me.

**Comment by shushmo** [comment]
Same issue on 4.0.9 
 `Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Nikse.SubtitleEdit.Core.AutoTranslate.ChatGptTranslate.<Translate>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nikse.SubtitleEdit.Forms.Translate.MergeAndSplitHelper.<MergeAndTranslateIfPossible>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
{
    "error": {
        "message": "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }`

**Comment by Tizioincognit0** [comment]
I'm facing a similar issue.
